name: My cool workflow

on:
  push:
  pull_request:
  workflow_dispatch:
  
jobs:
    myfistjob: 
              name: First job
              runs-on: ubuntu-latest
              steps:
              - name: Step One
                uses: actions/checkout@v3
              - name: Step Two
                run: | 
                  touch ${{secrets.MY_SECRET}}.yaml
                  echo "Please Alex is Friday let me escape" >> ${{secrets.MY_SECRET}}.yaml
                  cat newfile.yaml
                  pwd
    mysecondjob: 
              needs: [myfistjob]
              name: Second job
              runs-on: macos-latest
              steps:
              - name: Step One
                run: date
    mythirdjob: 
              name: Third job
              runs-on: windows-latest
              steps:
              - name: Step One
                run: date
               
